name: Application deployment

on:
  # idealy this should be prevented by protecting branches on github
  push:
    branches:
      - "main"
    paths:
      - 'application/**'
      - '.github/workflows/application.yml'

  pull_request:
    branches:
      - "main"
    paths:
      - 'application/**'
      - '.github/workflows/application.yml'

  workflow_dispatch:
   
jobs:
  application-deployment-simplified:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}} 

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    

      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'application'
          sparse-checkout-cone-mode: false

      - name: Setting up directory
        run: |
          cd application
          ls
          docker build . -t developmentdemoacr.azurecr.io/serverapp:${{ github.sha }}
          az acr list

      # - name: 'Build and push image'
      #   uses: azure/docker-login@v1
      # - run: |
      #       docker build . -t developmentdemoacr.azurecr.io/serverapp:${{ github.sha }}