name: Application deployment

on:
  # idealy this should be prevented by protecting branches on github
  push:
    branches:
      - "main"
    paths:
      - 'application/**'
      - '.github/workflows/application.yml'

  pull_request:
    branches:
      - "main"
    paths:
      - 'application/**'
      - '.github/workflows/application.yml'

  workflow_dispatch:
   
jobs:
  application-deployment-simplified:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}} 

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'application'
          sparse-checkout-cone-mode: false

      - name: Setting up directory
        run: |
          cd application
          ls
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
