name: Terraform deploy

on:
  push:
    branches:
      - "main"
    paths:
      - 'aks/**'
      - '.github/workflows/terraform.yml'

  pull_request:
    branches:
      - "main"
    paths:
      - 'aks/**'
      - '.github/workflows/terraform.yml'

  workflow_dispatch:
   
jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}} 
    steps:
      # Checkout project code
      # Use sparse checkout to only select files in mobile app directory
      # Turning off cone mode ensures that files in the project root are not included during checkout
      # - uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show      

      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'aks'
          sparse-checkout-cone-mode: false
      # - uses: actions/checkout@v2      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform simplified
              
        # terraform init -backend-config=../backend/${{ env.environment }}.conf --var-file="../envs/${{ env.environment }}.tfvars;"
        # terraform plan --var-file="../envs/${{ env.environment }}.tfvars" -lock=false ...
        # terraform apply --auto-approve --var-file="../envs/${{ env.environment }}.tfvars" -lock=false
        run: |
          cd aks
          terraform init
          terraform apply --auto-approve
          
