name: Terraform deploy

on:
  push:
    branches:
      - "main"
    paths:
      - 'aks/**'
      - '.github/workflows/terraform.yml'

  pull_request:
    branches:
      - "main"
    paths:
      - 'aks/**'
      - '.github/workflows/terraform.yml'

  workflow_dispatch:
   
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checkout project code
      # Use sparse checkout to only select files in mobile app directory
      # Turning off cone mode ensures that files in the project root are not included during checkout
      # - uses: actions/checkout@v3
      #   with:
      #     sparse-checkout: 'aks'
      #     sparse-checkout-cone-mode: false
      - uses: actions/checkout@v2      
      - name: Create annotation for build error
        run: ls          